### ISSUE TITLE
Getting "Must issue a STARTTLS command first" error

### ISSUE THREAD

**Issue by gbook** [xpeco/Email-Send-SMTP-Gmail#1]
Looks like a great package, but I'm getting the above error when trying to connect to smtp.gmail.com using the following line:

```
my ($mail,$error)=Email::Send::SMTP::Gmail->new( -smtp=>$cfg{'emailserver'}, -login=>$cfg{'emailusername'}, -pass=>$cfg{'emailpassword'});`
```

**Comment by xpeco** [comment]
Hi,

Actually, in some way [this issue is related to the SMTP server](https://www.google.es/search?client=ubuntu&channel=fs&q=must+issue+a+starttls+command+first) (and not with the module).
Are you using gmail.com?

Please enabled the debug option and force the port 587:

my $mail = Email::Send::SMTP::Gmail->new(-smtp=>$cfg{'emailserver'}, -login=>$cfg{'emailusername'}, -pass=>$cfg{'emailpassword'}, **-debug => 1 , -port => '587'** );

**Comment by gbook** [comment]
Forcing the port to 587 fixed it. Thank you!
